/* Generated by teamy-bend. Runtime support: MPL-2.0.
 * Input definitions retain their licenses; generation does not relicense them.
 * Portable baseline C11 runtime: no foreign calls or upstream optimizations. */
#include <stdint.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <setjmp.h>

#ifndef BEND_MAX_STEPS
#define BEND_MAX_STEPS 2000000u
#endif
#ifndef BEND_MAX_ALLOC
#define BEND_MAX_ALLOC 67108864u
#endif
#ifndef BEND_MAX_DEPTH
#define BEND_MAX_DEPTH 1024u
#endif
#ifndef BEND_MAX_OUTPUT
#define BEND_MAX_OUTPUT 8388608u
#endif

enum NodeKind { N_VAR, N_REF, N_LAM, N_APP, N_CTR, N_MAT, N_EFQ, N_LET, N_ERASED };
typedef struct {
  unsigned kind;
  size_t a, b;
  uint64_t id;
  size_t start, count;
  const char *name;
  size_t name_length;
} Expr;

/* BEND_GENERATED_TABLES */

typedef struct Thunk Thunk;
typedef struct Env Env;
typedef struct Value Value;
typedef struct Allocation Allocation;
enum ValueKind { V_CONSTRUCTOR, V_FUNCTION, V_ERASED };
struct Thunk { unsigned state; size_t expression; Env *environment; Value *value; };
struct Env { uint64_t id; Thunk *value; Env *next; };
struct Value { unsigned kind; const Expr *expression; Env *environment; Thunk **fields; };
struct Allocation { void *memory; Allocation *next; };

static Allocation *allocations = NULL;
static size_t allocated_bytes = 0;
static size_t steps = 0;
static size_t evaluation_depth = 0;
static jmp_buf failure;
static Thunk *definitions[BEND_DEFINITION_COUNT];
static Value erased = { V_ERASED, NULL, NULL, NULL };
static unsigned char output[BEND_MAX_OUTPUT];
static size_t output_length = 0;

static void fail(const char *message) {
  (void)fprintf(stderr, "teamy-bend generated program: %s\n", message);
  longjmp(failure, 1);
}

static void tick(void) {
  if (steps >= BEND_MAX_STEPS) fail("evaluation budget exhausted");
  ++steps;
}

static void enter(void) {
  tick();
  if (evaluation_depth >= BEND_MAX_DEPTH) fail("evaluation nesting limit exhausted");
  ++evaluation_depth;
}

static void *allocate(size_t size) {
  Allocation *record;
  void *memory;
  if (size > BEND_MAX_ALLOC || sizeof(Allocation) > BEND_MAX_ALLOC - size ||
      allocated_bytes > BEND_MAX_ALLOC - size - sizeof(Allocation)) {
    fail("allocation budget exhausted");
  }
  memory = calloc(1, size);
  if (!memory) fail("allocation failed");
  record = (Allocation *)malloc(sizeof(Allocation));
  if (!record) { free(memory); fail("allocation tracking failed"); }
  record->memory = memory;
  record->next = allocations;
  allocations = record;
  allocated_bytes += size + sizeof(Allocation);
  return memory;
}

static void release_all(void) {
  while (allocations) {
    Allocation *record = allocations;
    allocations = record->next;
    free(record->memory);
    free(record);
  }
  allocated_bytes = 0;
}

static Thunk *lazy(size_t expression, Env *environment) {
  Thunk *thunk = (Thunk *)allocate(sizeof(Thunk));
  thunk->expression = expression;
  thunk->environment = environment;
  return thunk;
}

static Env *bind(Env *outer, uint64_t id, Thunk *value) {
  Env *environment = (Env *)allocate(sizeof(Env));
  environment->id = id;
  environment->value = value;
  environment->next = outer;
  return environment;
}

static Thunk *lookup(Env *environment, uint64_t id) {
  while (environment) {
    tick();
    if (environment->id == id) return environment->value;
    environment = environment->next;
  }
  fail("unbound runtime variable");
  return NULL;
}

static Value *force(Thunk *thunk);

static Value *apply(Value *function, Thunk *argument) {
  const Expr *node;
  Value *result;
  enter();
  if (function->kind != V_FUNCTION) fail("application of a non-function");
  node = function->expression;
  if (node->kind == N_LAM) {
    result = force(lazy(node->a, bind(function->environment, node->id, argument)));
  } else if (node->kind == N_MAT) {
    Value *scrutinee = force(argument);
    if (scrutinee->kind != V_CONSTRUCTOR) fail("pattern match expected constructor data");
    if (scrutinee->expression->name_length == node->name_length &&
        memcmp(scrutinee->expression->name, node->name, node->name_length) == 0) {
      size_t index;
      result = force(lazy(node->a, function->environment));
      for (index = 0; index < scrutinee->expression->count; ++index) {
        result = apply(result, scrutinee->fields[index]);
      }
    } else {
      result = apply(force(lazy(node->b, function->environment)), argument);
    }
  } else {
    fail("entered an impossible match branch");
    return NULL;
  }
  --evaluation_depth;
  return result;
}

static Value *force(Thunk *thunk) {
  const Expr *node;
  Value *result;
  enter();
  if (thunk->state == 2) { --evaluation_depth; return thunk->value; }
  if (thunk->state == 1) fail("cyclic evaluation");
  thunk->state = 1;
  node = &program[thunk->expression];
  switch (node->kind) {
    case N_VAR:
      result = force(lookup(thunk->environment, node->id));
      break;
    case N_REF:
      result = force(definitions[node->a]);
      break;
    case N_LAM: case N_MAT: case N_EFQ:
      result = (Value *)allocate(sizeof(Value));
      result->kind = V_FUNCTION;
      result->expression = node;
      result->environment = thunk->environment;
      break;
    case N_APP:
      result = apply(force(lazy(node->a, thunk->environment)), lazy(node->b, thunk->environment));
      break;
    case N_CTR: {
      size_t index;
      result = (Value *)allocate(sizeof(Value));
      result->kind = V_CONSTRUCTOR;
      result->expression = node;
      if (node->count) {
        if (node->count > BEND_MAX_ALLOC / sizeof(Thunk *)) fail("constructor field budget exhausted");
        result->fields = (Thunk **)allocate(node->count * sizeof(Thunk *));
        for (index = 0; index < node->count; ++index) {
          result->fields[index] = lazy((size_t)links[node->start + index], thunk->environment);
        }
      }
      break;
    }
    case N_LET: {
      size_t index;
      Env *body_environment = thunk->environment;
      for (index = 0; index < node->count; ++index) {
        uint64_t id = links[node->start + index * 2];
        size_t expression = (size_t)links[node->start + index * 2 + 1];
        /* Every RHS closes over the original environment: simultaneous lets. */
        body_environment = bind(body_environment, id, lazy(expression, thunk->environment));
      }
      result = force(lazy(node->a, body_environment));
      break;
    }
    case N_ERASED:
      result = &erased;
      break;
    default:
      fail("unknown runtime instruction");
      return NULL;
  }
  thunk->value = result;
  thunk->state = 2;
  --evaluation_depth;
  return result;
}

static void emit_byte(unsigned char byte) {
  if (output_length >= BEND_MAX_OUTPUT) fail("output budget exhausted");
  output[output_length++] = byte;
}

static void emit_text(const char *text) {
  while (*text) emit_byte((unsigned char)*text++);
}

static void emit_string(const char *text, size_t length) {
  static const char hex[] = "0123456789abcdef";
  size_t index;
  emit_byte('"');
  for (index = 0; index < length; ++index) {
    unsigned char byte = (unsigned char)text[index];
    if (byte == '"' || byte == '\\') { emit_byte('\\'); emit_byte(byte); }
    else if (byte < 32) {
      emit_text("\\u00");
      emit_byte((unsigned char)hex[byte >> 4]);
      emit_byte((unsigned char)hex[byte & 15]);
    } else emit_byte(byte);
  }
  emit_byte('"');
}

static void materialize(Thunk *thunk, size_t depth) {
  Value *value;
  size_t index;
  tick();
  if (depth >= BEND_MAX_DEPTH) fail("result nesting limit exhausted");
  value = force(thunk);
  if (value->kind == V_ERASED) { emit_text("{\"erased\":true}"); return; }
  if (value->kind == V_FUNCTION) fail("standalone entry must return data, not a function");
  if (value->kind != V_CONSTRUCTOR) fail("standalone entry produced unsupported runtime data");
  emit_text("{\"constructor\":");
  emit_string(value->expression->name, value->expression->name_length);
  emit_text(",\"fields\":[");
  for (index = 0; index < value->expression->count; ++index) {
    if (index) emit_byte(',');
    materialize(value->fields[index], depth + 1);
  }
  emit_text("]}");
}

int main(void) {
  if (setjmp(failure) == 0) {
    size_t index;
    for (index = 0; index < BEND_DEFINITION_COUNT; ++index) definitions[index] = lazy(definition_roots[index], NULL);
    emit_text("{\"value\":");
    materialize(definitions[BEND_ENTRY_INDEX], 0);
    emit_text("}\n");
    if (fwrite(output, 1, output_length, stdout) != output_length || fflush(stdout) != 0) fail("output write failed");
    release_all();
    return 0;
  }
  release_all();
  return 1;
}
