// SPDX-License-Identifier: Apache-2.0
// Native C representation derived from Bend 2.0.5, Copyright 2026 HigherOrderCO.
// Rust translation and changes: TeamDman. See NOTICE and licenses/Apache-2.0.txt.
//! Checked executable lowering into the packed native C foreign ABI.

use super::CompileError;
use super::executable_c_foreign;
use super::executable_c_layout::ConstructorTable;
use super::executable_c_layout::Kind;
use super::executable_c_layout::Layout;
use super::executable_c_layout::Layouts;
use crate::kernel::Binder;
use crate::kernel::ExecutableBook;
use crate::kernel::ExecutableEntry;
use crate::kernel::Quant;
use crate::kernel::Term;
use crate::kernel::TermRef;
use crate::kernel::elaborate::DefinitionBody;
use crate::kernel::elaborate::ExecutableProgram;
use crate::kernel::elaborate::Expression;
use crate::kernel::elaborate::ExpressionKind;
use crate::kernel::substitute;
use std::collections::BTreeMap;
use std::collections::BTreeSet;
use std::fmt::Write;
use std::rc::Rc;

#[path = "executable_c_native.rs"]
mod native;
#[path = "executable_c_values.rs"]
mod values;

type Scope = BTreeMap<usize, String>;
type Substitutions = BTreeMap<usize, TermRef>;

/// Generate a standalone C program from an execution-only checked book.
///
/// Foreign source is embedded without executing it during compilation. Its
/// contracts remain runtime assumptions, separate from strict proof evidence.
/// The native ABI uses packed Terms, flattened constructor fields and unary
/// closures. The bounded CPU runtime does not implement GPU offload.
///
/// # Errors
/// Rejects unsupported reachable contracts, invalid layouts, unavailable C
/// imports and exhausted compiler budgets before producing an output program.
pub fn compile_executable_c(book: &ExecutableBook) -> Result<String, CompileError> {
    let program = book
        .lower_for_compilation()
        .map_err(|error| CompileError::new(error.to_string()))?;
    let table = ConstructorTable::build(&program)?;
    let foreign = executable_c_foreign::assemble(&program, &table)?;
    let mut generator = Generator {
        program: &program,
        table,
        layouts: Layouts::new(&program),
        definitions: Vec::new(),
        definition_ids: BTreeMap::new(),
        closures: Vec::new(),
        conversions: Vec::new(),
        conversion_ids: BTreeMap::new(),
        printers: Vec::new(),
        printer_ids: BTreeMap::new(),
        nodes: 0,
    };
    let entry = if program.entry == ExecutableEntry::Missing {
        None
    } else {
        Some(generator.definition("main", &Substitutions::new())?)
    };
    let printer = if program.entry == ExecutableEntry::Pure {
        Some(generator.printer(&program.definitions["main"].ty, 0)?)
    } else {
        None
    };
    let mut source = String::from(
        "/* Generated by teamy-bend. Input imports retain their own licences. */\n#ifdef _MSC_VER\n#define _CRT_SECURE_NO_WARNINGS\n#endif\n#include <stdint.h>\n",
    );
    source.push_str(&generator.table.declarations());
    source.push_str(include_str!("executable_core.c"));
    source.push_str(include_str!("executable_io.c"));
    source.push_str(include_str!("executable_files.c"));
    source.push_str(include_str!("executable_network.c"));
    source.push_str(include_str!("executable_c_numeric.c"));
    source.push_str(include_str!("executable_c_bridge.c"));
    source.push_str(&foreign.source);
    generator.prototypes(&mut source);
    for definition in &generator.definitions {
        source.push_str(definition);
    }
    for closure in &generator.closures {
        source.push_str(&closure.source);
    }
    for conversion in &generator.conversions {
        source.push_str(conversion);
    }
    for printer in &generator.printers {
        source.push_str(printer);
    }
    source.push_str("static void tb_initialize(Env e) {\n  (void)e;\n  tb_register_builtins();\n");
    for (index, closure) in generator.closures.iter().enumerate() {
        writeln!(
            source,
            "  tb_register_closure({}, tb_function_{index}, {});",
            index + 2,
            closure.captures
        )
        .unwrap();
    }
    for initializer in &foreign.initializers {
        writeln!(source, "  {initializer}();").unwrap();
    }
    for cid in foreign.requests.values() {
        writeln!(source, "  tb_require_effect({cid});").unwrap();
    }
    source.push_str("}\n");
    if let Some(printer) = printer {
        writeln!(source, "static void tb_show_main(Env e, Term value) {{ tb_show_{printer}(&e, value, 0, 0); tb_show_text(\"\\n\"); }}").unwrap();
    }
    let entry = entry.map_or_else(
        || "NULL".to_owned(),
        |id| {
            writeln!(
                source,
                "static Term tb_entry(Env e) {{ return tb_definition_{id}(&e); }}"
            )
            .unwrap();
            "tb_entry".to_owned()
        },
    );
    writeln!(
        source,
        "int main(void) {{ return tb_run({entry}, {}, {}, tb_initialize); }}",
        usize::from(program.entry == ExecutableEntry::Io),
        if printer.is_some() {
            "tb_show_main"
        } else {
            "NULL"
        }
    )
    .unwrap();
    Ok(source)
}

struct Closure {
    source: String,
    captures: usize,
}

/// Generated values live in a tracked scratch frame, never in a C array whose
/// size grows with the input program. The wrapper stays small even when a body
/// has thousands of temporaries, and owns cleanup across every body return.
struct Body {
    text: String,
    slots: usize,
}

#[derive(Clone, Copy)]
enum FunctionResult {
    Term,
    Void,
}

impl Body {
    fn new(text: &str) -> Self {
        Self {
            text: text.to_owned(),
            slots: 0,
        }
    }

    fn reserve(&mut self, count: usize) -> usize {
        let start = self.slots;
        self.slots += count;
        start
    }

    fn push_str(&mut self, text: &str) {
        self.text.push_str(text);
    }

    fn function(
        self,
        name: &str,
        parameters: &str,
        arguments: &str,
        result: FunctionResult,
    ) -> String {
        let returns_term = matches!(result, FunctionResult::Term);
        let result_type = if returns_term { "Term" } else { "void" };
        let mut source = format!(
            "static TB_NOINLINE {result_type} {name}_body({parameters}, Term *tb_values) {{\n  (void)tb_values;\n{} }}\nstatic TB_NOINLINE {result_type} {name}({parameters}) {{\n  Term *tb_values = tb_frame_push({});\n",
            self.text, self.slots
        );
        if returns_term {
            writeln!(source, "  Term tb_result = {name}_body({arguments}, tb_values);\n  tb_frame_pop(tb_values);\n  return tb_result;\n}}").unwrap();
        } else {
            writeln!(
                source,
                "  {name}_body({arguments}, tb_values);\n  tb_frame_pop(tb_values);\n}}"
            )
            .unwrap();
        }
        source
    }
}

impl Write for Body {
    fn write_str(&mut self, s: &str) -> std::fmt::Result {
        self.text.push_str(s);
        Ok(())
    }
}

struct Generator<'a> {
    program: &'a ExecutableProgram,
    table: ConstructorTable,
    layouts: Layouts<'a>,
    definitions: Vec<String>,
    definition_ids: BTreeMap<String, usize>,
    closures: Vec<Closure>,
    conversions: Vec<String>,
    conversion_ids: BTreeMap<String, usize>,
    printers: Vec<String>,
    printer_ids: BTreeMap<String, usize>,
    nodes: usize,
}

impl Generator<'_> {
    fn prototypes(&self, source: &mut String) {
        for index in 0..self.definitions.len() {
            writeln!(
                source,
                "static TB_NOINLINE Term tb_definition_{index}(const Env *e);"
            )
            .unwrap();
        }
        for index in 0..self.closures.len() {
            writeln!(
                source,
                "static TB_NOINLINE Term tb_function_{index}(Env e, const Term *captures, Term argument);"
            )
            .unwrap();
        }
        for index in 0..self.conversions.len() {
            writeln!(source, "static TB_NOINLINE Term tb_box_{index}(const Env *e, const Term *input);\nstatic TB_NOINLINE void tb_unbox_{index}(const Env *e, Term value, Term *output);").unwrap();
        }
        for index in 0..self.printers.len() {
            writeln!(
                source,
                "static TB_NOINLINE void tb_show_{index}(const Env *e, Term value, unsigned depth, char chain);"
            )
            .unwrap();
        }
    }

    fn fresh(&mut self) -> Result<String, CompileError> {
        self.nodes += 1;
        if self.nodes > 250_000 {
            return Err(CompileError::new(
                "executable C generation budget exhausted",
            ));
        }
        Ok(format!("t{}", self.nodes))
    }

    fn hold(&mut self, output: &mut Body, expression: &str) -> Result<String, CompileError> {
        self.fresh()?;
        let name = format!("tb_values[{}]", output.reserve(1));
        writeln!(output, "  {name} = {expression};").unwrap();
        Ok(name)
    }

    fn array(&mut self, output: &mut Body, values: &[String]) -> Result<String, CompileError> {
        self.fresh()?;
        let start = output.reserve(values.len().max(1));
        if values.is_empty() {
            writeln!(output, "  tb_values[{start}] = 0;").unwrap();
        } else {
            for (index, value) in values.iter().enumerate() {
                writeln!(output, "  tb_values[{}] = {value};", start + index).unwrap();
            }
        }
        Ok(format!("(tb_values + {start})"))
    }

    fn definition(
        &mut self,
        name: &str,
        substitutions: &Substitutions,
    ) -> Result<usize, CompileError> {
        let key = format!("{name}:{substitutions:?}");
        if let Some(index) = self.definition_ids.get(&key) {
            return Ok(*index);
        }
        if self.definitions.len() >= 4096 {
            return Err(CompileError::new(
                "executable C specialization budget exhausted",
            ));
        }
        let index = self.definitions.len();
        self.definitions.push(String::new());
        self.definition_ids.insert(key, index);
        let definition = self
            .program
            .definitions
            .get(name)
            .ok_or_else(|| CompileError::new(format!("missing executable definition {name}")))?
            .clone();
        let mut output = Body::new("  (void)e;\n  tb_tick();\n");
        let live = definition
            .parameters
            .iter()
            .filter(|parameter| parameter.quant != Quant::None)
            .count();
        let value = match definition.body {
            DefinitionBody::OpaqueType(_) => "0".to_owned(),
            DefinitionBody::Foreign(_) => {
                let cid = self.table.get(name)?.cid;
                self.curry(live + 1, &mut output, &mut |generator, arguments, body| {
                    let fields = generator.array(body, arguments)?;
                    generator.hold(
                        body,
                        &format!(
                            "tb_c_construct(e, {cid}, {}, {fields}, false)",
                            arguments.len()
                        ),
                    )
                })?
            }
            DefinitionBody::Numeric(intrinsic) => {
                self.curry(live, &mut output, &mut |generator, arguments, body| {
                    generator.numeric(intrinsic, arguments, body)
                })?
            }
            DefinitionBody::Ordinary(body) => {
                let ty = specialize_type(&definition.ty, substitutions);
                if self.program.base_names.contains(name) && native::optimized(name) {
                    self.curry(live, &mut output, &mut |generator, arguments, body| {
                        generator.native(name, &ty, arguments, body)
                    })?
                } else {
                    self.expression(
                        &specialize_expression(&body, substitutions),
                        &Scope::new(),
                        &mut output,
                    )?
                }
            }
        };
        writeln!(output, "  return {value};").unwrap();
        self.definitions[index] = output.function(
            &format!("tb_definition_{index}"),
            "const Env *e",
            "e",
            FunctionResult::Term,
        );
        Ok(index)
    }

    fn curry<F>(
        &mut self,
        arity: usize,
        output: &mut Body,
        final_body: &mut F,
    ) -> Result<String, CompileError>
    where
        F: FnMut(&mut Self, &[String], &mut Body) -> Result<String, CompileError>,
    {
        self.curry_at(arity, &[], output, final_body)
    }

    fn curry_at<F>(
        &mut self,
        arity: usize,
        arguments: &[String],
        output: &mut Body,
        final_body: &mut F,
    ) -> Result<String, CompileError>
    where
        F: FnMut(&mut Self, &[String], &mut Body) -> Result<String, CompileError>,
    {
        if arguments.len() == arity {
            return final_body(self, arguments, output);
        }
        let id = self.reserve_closure(arguments.len())?;
        let mut body = Body::new("  (void)e; (void)captures; (void)argument;\n");
        let mut next = (0..arguments.len())
            .map(|index| format!("captures[{index}]"))
            .collect::<Vec<_>>();
        next.push("argument".to_owned());
        let value = self.curry_at(arity, &next, &mut body, final_body)?;
        writeln!(body, "  return {value};").unwrap();
        self.closures[id].source = closure_source(id, body);
        self.make_closure(id, arguments, output)
    }

    fn reserve_closure(&mut self, captures: usize) -> Result<usize, CompileError> {
        if self.closures.len() >= 65534 || captures > 254 {
            return Err(CompileError::new(
                "executable C closure table or capture arity exhausted",
            ));
        }
        let id = self.closures.len();
        self.closures.push(Closure {
            source: String::new(),
            captures,
        });
        Ok(id)
    }

    fn make_closure(
        &mut self,
        id: usize,
        captures: &[String],
        output: &mut Body,
    ) -> Result<String, CompileError> {
        let array = self.array(output, captures)?;
        self.hold(
            output,
            &format!("tb_c_closure(e, {}, {}, {array})", id + 2, captures.len()),
        )
    }

    fn closure(
        &mut self,
        expression: &Expression,
        parameter: usize,
        scope: &Scope,
        output: &mut Body,
    ) -> Result<String, CompileError> {
        let mut used = BTreeSet::new();
        variables(expression, &mut used);
        let captures = scope
            .iter()
            .filter(|(id, _)| **id != parameter && used.contains(id))
            .collect::<Vec<_>>();
        let id = self.reserve_closure(captures.len())?;
        let mut inner = Scope::new();
        for (index, (variable, _)) in captures.iter().enumerate() {
            inner.insert(**variable, format!("captures[{index}]"));
        }
        inner.insert(parameter, "argument".into());
        let mut body = Body::new("  (void)e; (void)captures; (void)argument;\n");
        let value = match &expression.kind {
            ExpressionKind::Lambda {
                body: expression, ..
            } => self.expression(expression, &inner, &mut body)?,
            ExpressionKind::Match { .. } | ExpressionKind::Absurd { .. } => {
                self.match_body(expression, &inner, &mut body)?
            }
            _ => return Err(CompileError::new("invalid executable C closure node")),
        };
        writeln!(body, "  return {value};").unwrap();
        self.closures[id].source = closure_source(id, body);
        let values = captures
            .iter()
            .map(|(_, value)| (*value).clone())
            .collect::<Vec<_>>();
        self.make_closure(id, &values, output)
    }

    #[expect(
        clippy::too_many_lines,
        reason = "The complete typed IR traversal keeps argument erasure, specialization and evaluation order together."
    )]
    fn expression(
        &mut self,
        expression: &Expression,
        scope: &Scope,
        output: &mut Body,
    ) -> Result<String, CompileError> {
        self.fresh()?;
        match &expression.kind {
            ExpressionKind::Erased => Ok("0".to_owned()),
            ExpressionKind::Variable(id) => scope
                .get(id)
                .cloned()
                .ok_or_else(|| CompileError::new(format!("unbound executable C variable {id}"))),
            ExpressionKind::Definition(name) => {
                let id = self.definition(name, &Substitutions::new())?;
                self.hold(output, &format!("tb_definition_{id}(e)"))
            }
            ExpressionKind::Lambda { parameter, body } if parameter.quant == Quant::None => {
                self.expression(body, scope, output)
            }
            ExpressionKind::Lambda { parameter, .. }
            | ExpressionKind::Match { parameter, .. }
            | ExpressionKind::Absurd { parameter, .. } => {
                self.closure(expression, parameter.id, scope, output)
            }
            ExpressionKind::Apply { .. } => {
                let mut arguments = Vec::new();
                let mut head = expression;
                while let ExpressionKind::Apply {
                    function,
                    argument,
                    quant,
                } = &head.kind
                {
                    arguments.push((argument.as_ref(), *quant));
                    head = function;
                }
                arguments.reverse();
                let mut function = if let ExpressionKind::Definition(name) = &head.kind {
                    let definition = &self.program.definitions[name];
                    let substitutions = definition
                        .parameters
                        .iter()
                        .zip(&arguments)
                        .filter(|(parameter, (_, quant))| {
                            parameter.quant == Quant::None && *quant == Quant::None
                        })
                        .map(|(parameter, (argument, _))| {
                            (parameter.id, Rc::clone(&argument.source))
                        })
                        .collect();
                    let id = self.definition(name, &substitutions)?;
                    self.hold(output, &format!("tb_definition_{id}(e)"))?
                } else {
                    self.expression(head, scope, output)?
                };
                for (argument, quant) in arguments {
                    if quant == Quant::None {
                        continue;
                    }
                    let argument = self.expression(argument, scope, output)?;
                    function =
                        self.hold(output, &format!("tb_c_apply(e, {function}, {argument})"))?;
                }
                Ok(function)
            }
            ExpressionKind::Constructor {
                owner,
                name,
                fields,
            } => {
                if self.program.base_names.contains(owner)
                    && matches!(owner.as_str(), "U32" | "F32")
                    && fields.len() == 1
                    && let Some(word) = word_literal(self.program, &fields[0].value)
                {
                    return Ok(format!("UINT64_C({word})"));
                }
                let values = fields
                    .iter()
                    .filter(|field| field.binder.quant != Quant::None)
                    .map(|field| self.expression(&field.value, scope, output))
                    .collect::<Result<Vec<_>, _>>()?;
                if self.program.base_names.contains(owner) {
                    match owner.as_str() {
                        "Nat" => {
                            return if values.is_empty() {
                                Ok("0".into())
                            } else {
                                self.hold(output, &format!("tb_c_nat_chk(e, {} + 1)", values[0]))
                            };
                        }
                        "U32" | "F32" => {
                            return self.hold(output, &format!("tb_c_term_word(e, {})", values[0]));
                        }
                        "Array" => {
                            return self.array_constructor(name, &expression.ty, &values, output);
                        }
                        _ => (),
                    }
                }
                self.construct(name, &values, output)
            }
            ExpressionKind::Let { bindings, body } => {
                let mut inner = scope.clone();
                for binding in bindings
                    .iter()
                    .filter(|binding| binding.binder.quant != Quant::None)
                {
                    let value = self.expression(&binding.value, scope, output)?;
                    inner.insert(binding.binder.id, value);
                }
                self.expression(body, &inner, output)
            }
        }
    }

    fn match_body(
        &mut self,
        expression: &Expression,
        scope: &Scope,
        output: &mut Body,
    ) -> Result<String, CompileError> {
        let ExpressionKind::Match {
            parameter,
            owner,
            constructor,
            fields,
            arm,
            fallback,
        } = &expression.kind
        else {
            return Ok("tb_impossible()".into());
        };
        if parameter.quant == Quant::None {
            return Err(CompileError::new(
                "executable C cannot match an erased scrutinee",
            ));
        }
        let value = &scope[&parameter.id];
        writeln!(output, "  tb_reject_request({value});").unwrap();
        let condition = if self.program.base_names.contains(owner) {
            match owner.as_str() {
                "Nat" => format!(
                    "{value} {} 0",
                    if constructor == "Zero" { "==" } else { "!=" }
                ),
                "U32" | "F32" => "1".into(),
                "Array" => {
                    let (_, lgs, _) = self.array_layout(&parameter.ty)?;
                    format!(
                        "blk_cls({value}) {} {lgs}",
                        if constructor == "ALeaf" { "==" } else { "!=" }
                    )
                }
                _ => format!("term_aux({value}) == {}", self.table.get(constructor)?.cid),
            }
        } else {
            format!("term_aux({value}) == {}", self.table.get(constructor)?.cid)
        };
        let result = self.hold(output, "0")?;
        if condition != "1" {
            writeln!(output, "  if ({condition}) {{").unwrap();
        }
        let values = if self.program.base_names.contains(owner) {
            match owner.as_str() {
                "Nat" => {
                    if constructor == "Zero" {
                        Vec::new()
                    } else {
                        vec![format!("({value} - 1)")]
                    }
                }
                "U32" | "F32" => vec![self.hold(output, &format!("tb_c_word(e, (u32){value})"))?],
                "Array" => self.array_fields(constructor, &parameter.ty, value, output)?,
                _ => self.fields(constructor, value, output)?,
            }
        } else {
            self.fields(constructor, value, output)?
        };
        if values.len()
            != fields
                .iter()
                .filter(|field| field.quant != Quant::None)
                .count()
        {
            return Err(CompileError::new(
                "C match field arity differs from its layout",
            ));
        }
        let mut branch = self.expression(arm, scope, output)?;
        for field in values {
            branch = self.hold(output, &format!("tb_c_apply(e, {branch}, {field})"))?;
        }
        if condition == "1" {
            return Ok(branch);
        }
        writeln!(output, "  {result} = {branch};\n  }} else {{").unwrap();
        let branch = self.expression(fallback, scope, output)?;
        writeln!(
            output,
            "  {result} = tb_c_apply(e, {branch}, {value});\n  }}"
        )
        .unwrap();
        Ok(result)
    }
}

fn closure_source(id: usize, body: Body) -> String {
    let mut source = body.function(
        &format!("tb_function_{id}_inner"),
        "const Env *e, const Term *captures, Term argument",
        "e, captures, argument",
        FunctionResult::Term,
    );
    writeln!(source, "static TB_NOINLINE Term tb_function_{id}(Env e, const Term *captures, Term argument) {{\n  return tb_function_{id}_inner(&e, captures, argument);\n}}").unwrap();
    source
}

fn variables(expression: &Expression, output: &mut BTreeSet<usize>) {
    match &expression.kind {
        ExpressionKind::Variable(id) => {
            output.insert(*id);
        }
        ExpressionKind::Lambda { body, .. } => variables(body, output),
        ExpressionKind::Apply {
            function, argument, ..
        } => {
            variables(function, output);
            variables(argument, output);
        }
        ExpressionKind::Constructor { fields, .. } => {
            for field in fields {
                variables(&field.value, output);
            }
        }
        ExpressionKind::Match { arm, fallback, .. } => {
            variables(arm, output);
            variables(fallback, output);
        }
        ExpressionKind::Let { bindings, body } => {
            for field in bindings {
                variables(&field.value, output);
            }
            variables(body, output);
        }
        ExpressionKind::Erased | ExpressionKind::Definition(_) | ExpressionKind::Absurd { .. } => {}
    }
}

fn replace_type(ty: &TermRef, substitutions: &Substitutions) -> TermRef {
    substitutions
        .iter()
        .fold(Rc::clone(ty), |ty, (id, value)| substitute(&ty, *id, value))
}

fn specialize_type(ty: &TermRef, substitutions: &Substitutions) -> TermRef {
    if let Term::All { id, body, .. } = ty.as_ref()
        && let Some(argument) = substitutions.get(id)
    {
        return specialize_type(&substitute(body, *id, argument), substitutions);
    }
    replace_type(ty, substitutions)
}

fn specialize_binder(binder: &Binder, substitutions: &Substitutions) -> Binder {
    let mut result = binder.clone();
    result.ty = replace_type(&binder.ty, substitutions);
    result
}

fn specialize_expression(expression: &Expression, substitutions: &Substitutions) -> Expression {
    if let ExpressionKind::Lambda { parameter, body } = &expression.kind
        && parameter.quant == Quant::None
        && substitutions.contains_key(&parameter.id)
    {
        return specialize_expression(body, substitutions);
    }
    let mut result = expression.clone();
    result.ty = specialize_type(&result.ty, substitutions);
    result.source = replace_type(&result.source, substitutions);
    match &mut result.kind {
        ExpressionKind::Lambda { parameter, body } => {
            *parameter = specialize_binder(parameter, substitutions);
            **body = specialize_expression(body, substitutions);
        }
        ExpressionKind::Apply {
            function, argument, ..
        } => {
            **function = specialize_expression(function, substitutions);
            **argument = specialize_expression(argument, substitutions);
        }
        ExpressionKind::Constructor { fields, .. } => {
            for field in fields {
                field.binder = specialize_binder(&field.binder, substitutions);
                field.value = specialize_expression(&field.value, substitutions);
            }
        }
        ExpressionKind::Match {
            parameter,
            fields,
            arm,
            fallback,
            ..
        } => {
            *parameter = specialize_binder(parameter, substitutions);
            for field in fields {
                *field = specialize_binder(field, substitutions);
            }
            **arm = specialize_expression(arm, substitutions);
            **fallback = specialize_expression(fallback, substitutions);
        }
        ExpressionKind::Absurd { parameter, .. } => {
            *parameter = specialize_binder(parameter, substitutions);
        }
        ExpressionKind::Let { bindings, body } => {
            for field in bindings {
                field.binder = specialize_binder(&field.binder, substitutions);
                field.value = specialize_expression(&field.value, substitutions);
            }
            **body = specialize_expression(body, substitutions);
        }
        ExpressionKind::Erased | ExpressionKind::Variable(_) | ExpressionKind::Definition(_) => (),
    }
    result
}

fn word_literal(program: &ExecutableProgram, mut expression: &Expression) -> Option<u32> {
    let mut word = 0;
    for bit in 0..32 {
        let ExpressionKind::Constructor {
            owner,
            name,
            fields,
        } = &expression.kind
        else {
            return None;
        };
        if owner != "Word.Con"
            || name != "WCon"
            || fields.len() != 2
            || !program.base_names.contains(owner)
        {
            return None;
        }
        let ExpressionKind::Constructor {
            owner,
            name,
            fields: bits,
        } = &fields[0].value.kind
        else {
            return None;
        };
        if owner != "Bool" || !program.base_names.contains(owner) || !bits.is_empty() {
            return None;
        }
        match name.as_str() {
            "True" => word |= 1 << bit,
            "False" => (),
            _ => return None,
        }
        expression = &fields[1].value;
    }
    matches!(&expression.kind, ExpressionKind::Constructor { owner, name, fields } if owner == "Word.Nil" && name == "WNil" && fields.is_empty() && program.base_names.contains(owner)).then_some(word)
}

fn c_string(value: &str) -> String {
    let mut output = String::from("\"");
    for byte in value.bytes() {
        write!(output, "\\{byte:03o}").unwrap();
    }
    output.push('"');
    output
}
